### ISSUE TITLE
README に運用の手順を書いておく

### ISSUE THREAD

**Issue by tyru** [vim-jp/slacklog-generator#10]
今は vim-jp.github.io と同じ内容になってしまっているので。

## 何を書く？

* [x] サイトに反映させるまでの手順 (Contribution)
  * [ローカル環境構築](https://github.com/vim-jp/vim-jp.github.io/wiki/EditSite)
  * サイト生成
  * git push
  * ...
* [x] ~ブランチ運用~ #51 に分離
* [x] 各環境変数の説明
* [x] ~構成図 (ローカル PC, Jekyll?, Backend?, GitHub Actions?, GitHub Pages)~ #52 へ分離
  * 今のところは Jekyll で GitHub Pages にページ生成のみ
  * ちなみに blockdiag が簡単でおすすめ

**Comment by koron** [comment]
残タスクを #51 と #52 に分離派生させたのでこちらの issue は閉じます。
