### ISSUE TITLE
PR による既存の html ファイルに対する diff を表示させる

### ISSUE THREAD

**Issue by tyru** [vim-jp/slacklog-generator#11]
* CI の出力等 public な場所に表示するのは NG (削除対応がしづらい・不可能になるため)
* 案
  * slack の private channel
  * GitHub Team Discussion
    * https://github.com/orgs/vim-jp/teams/slacklog

## 参照

https://vim-jp.slack.com/archives/CRNLJDTU1/p1587506144302700

**Comment by koron** [comment]
`jekyll build` の結果に対する diff を出す site_diff.sh を作ってます。

**Comment by koron** [comment]
#27 で site_diff.sh 作りました。

あとは Actions から実行して出すことかしらね?

**Comment by koron** [comment]
#34 で Actions で差分作って Artifacts にアップするようにしました。
#34がマージされたら、この issue は閉じちゃってください。
