### ISSUE TITLE
reviewdog のGitHub Actions を設定する

### ISSUE THREAD

**Issue by koron** [vim-jp/slacklog-generator#117]
https://github.com/reviewdog/action-staticcheck

設定はここらへんからパクると速いかも。

https://github.com/reviewdog/action-staticcheck/blob/master/.github/workflows/reviewdog.yml

**Comment by raa0121** [comment]
https://github.com/reviewdog/action-golangci-lint/blob/master/.github/workflows/reviewdog.yml
golangci-lint を使ったほうがいいですかね？

**Comment by koron** [comment]
基本的に全部丸コピーして動かして、余分なものを落とすのが良いのかなって思います。

**Comment by koron** [comment]
#128 で完了しました。
