### ISSUE TITLE
Bot のアイコンが表示されない

### ISSUE THREAD

**Issue by tyru** [vim-jp/slacklog-generator#14]
https://vim-jp.org/slacklog/C03C4RC9F/2020/04/index.html#ts-1586008227.425200

**Comment by thinca** [comment]
reminder は Slack 組み込みなので他と違う部分があるのかもしれない。

**Comment by thinca** [comment]
調査しました。
こいつらは `user` = `USLACKBOT` と言う名前です。(これは user id)
export したログに含まれる users.json にはこいつの情報が含まれていません。
しかし API で取得したユーザー一覧にはこいつが含まれていることを確認しました。よって users.json を API で更新する運用に入れば解決しそうです。

**Comment by koron** [comment]
これに関して API で取った値はそうそう変わらないと仮定できそうだし、
まずは手動で取ったやつを固定で足しちゃったらどうだろか?
ファイルから読んだ直後に直接コードで足しちゃうの。

こんな感じでさ

```go
// NewUserTable : pathに指定したJSON形式のユーザデータを読み込み、UserTableを生
// 成する。
func NewUserTable(path string) (*UserTable, error) {
	var users []User
	err := ReadFileAsJSON(path, &users)
	if err != nil {
		return nil, err
	}

	// 固定ユーザ!!!
	users = append(users, User{
		ID: 123,
		Name: "USLACKBOT",
		// ...(snip)...
	})

	userMap := make(map[string]*User, len(users))
	for i, u := range users {
		pu := &users[i]
		userMap[u.ID] = pu
		if u.Profile.BotID != "" {
			userMap[u.Profile.BotID] = pu
		}
	}
	return &UserTable{users, userMap}, nil
}
```

**Comment by thinca** [comment]
将来的に勝手に直るし、今見れなくてもそこまで困らないので、何もしない、でいいかなと思います。最終的に直ったタイミングで閉じてしまえばよさそうです。

**Comment by thinca** [comment]
users.json を API で更新するようにしたので、見れるようになりました。
