### ISSUE TITLE
月を跨いだスレッドの返信が表示されない

### ISSUE THREAD

**Issue by thinca** [vim-jp/slacklog-generator#17]
(コードを見た限り…実際に事例を確認してないので要確認)

スレッドに対して翌月に返信があった場合、その message データは前の月の JSON には入っていないので、前の月のスレッドには表示されない、はず。たぶん。

**Comment by koron** [comment]
どっか事例が欲しいな…

**Comment by koron** [comment]
* スレッドのメッセージ配列は `MessageTable.ThreadMap` に thread timestamp をキーに格納されている
* `MessageTable` は各チャンネル毎に生成されている
* `MessageTable.ReadLogDir()` はチャンネルの全ログファイル(日や月を跨いで)読み込んでる

以上のことから月跨ぎのスレッドも正しく1つのスレッドになっていると考えられます。

@thinca コードのどの部分から月跨ぎのスレッドができないと判断したのか詳しく書いてもらえませんか?

**Comment by koron** [comment]
![image](https://user-images.githubusercontent.com/468368/81067384-8f56b480-8f19-11ea-9ac7-b28a5898acfc.png)

無理やり月跨ぎのスレッド作ってもちゃんと出たので worksforme で閉じます。
