### ISSUE TITLE
脱 Jekyll

### ISSUE THREAD

**Issue by tyru** [vim-jp/slacklog-generator#18]
## Why

* デリミタが2つ混じってるのはややこしい
* シンタックスハイライトが壊れる

## 要件

* [x] `./scripts/generate_html.sh` だけで完全な html を生成する
* [x] ~serve サブコマンド追加 (jekyll serve 相当)~ #49 へ分離した

sitemap.xml は一旦無視する。
（どうせ今は Google 検索 vim-jp/slacklog-generator#7 できるようになってないし）

## 参照

このあたりから
https://vim-jp.slack.com/archives/CRNLJDTU1/p1588084267165000

**Comment by koron** [comment]
> デリミタが2つ混じってるのはややこしい
> シンタックスハイライトが壊れる

この2点に関しては #26 で解決しました。

**Comment by kuuote** [comment]
#39 で`generator.go` から`site.baseurl`だけ取り除きました

**Comment by koron** [comment]
終わったので閉じます。
