### ISSUE TITLE
添付ファイル対応

### ISSUE THREAD

**Issue by tyru** [vim-jp/slacklog-generator#2]
* [x] ~mimetype =~ '^text/' は fetch して .html に埋め込み~ #54 へ分割
* [x] mimetype =~ '^image/' は `<img>` で参照
* [x] mimetype =~ '^video/' は `<video>` で参照
* [x] URL のトークンパラメータは消す
  * パラメータがなくても vim-jp.slack.com にログインしていれば見れる
* [x] ~添付ファイルの横に「？」アイコンを表示して↓をホバーで表示~ #55 へ分離
  * `画像が見れない場合 vim-jp.slack.com にログインすると見れるようになります`

**Comment by koron** [comment]
残件は #54 と #55 に分割派生させましたので、こちらは閉じます。
