### ISSUE TITLE
テンプレートを分離する

### ISSUE THREAD

**Issue by tennashi** [vim-jp/slacklog-generator#21]
特に `channel_per_month_index.tmpl` の制御構文の嵐が辛くなってきている

https://vim-jp.slack.com/archives/CRNLJDTU1/p1588580059231100
https://vim-jp.slack.com/archives/CRNLJDTU1/p1588580695234700

案:
テンプレートを
* `channel_per_month/index.html` : ヘッダフッタや次の月へのリンクなどを定義
* `channel_per_month/user_icon.html` : メッセージのユーザアイコン部分
* `channel_per_month/attachment.html` : 添付ファイル部分
* `channel_per_month/reaction.html`: リアクション部分
に分割する

// 分割の方法は一例なので、必要に応じてさらに分割を検討する

**Comment by koron** [comment]
まずは完全な分離ではなくメイン生成部分(slacklog_template)をGoだけでやるようにする。
具体的には `site.url` などを Go の template parameter として提供し
``{{ site.url }}` から `<<- .site.url >>` に書き換える。
次に `<<- ... ->>` を `{{ ... }}` に一気に置き換える。

**Comment by koron** [comment]
対象テンプレート 

* `site.baseurl`
* `post.url`
* `page.title`

**Comment by koron** [comment]
あー #26 でやった内容とは意味合いが違った。

あっちはテンプレートの表記を統一していじりやすくした。

こっちはそのそもテンプレートを複数ファイルに分ける話だったので
assign外れます。

**Comment by koron** [comment]
もろもろ準備整いそうなのでやるよ。
