### ISSUE TITLE
文字が表示されない

### ISSUE THREAD

**Issue by heavenshell** [vim-jp/slacklog-generator#29]
本文の中の絵文字のパスが多分おかしい。
```
https://vim-jp.org/slacklog/emojis/wakaranaihttps://emoji.slack-edge.com/T03C4RC8V/wakaranai/e83e019938fa08e0.png
```

みたいになっていて、表示できないので、直して欲しいです。
<img width="940" alt="スクリーンショット 2020-05-05 21 49 58" src="https://user-images.githubusercontent.com/56591/81067888-6256d180-8f1a-11ea-84e5-a7bcb18f4adb.png">

**Comment by thinca** [comment]
log-data に入ってる emoji.json の中身がおかしい。直します。

**Comment by thinca** [comment]
@heavenshell たぶん直ったので確認してもらっていいですか?

**Comment by heavenshell** [comment]
<img width="342" alt="スクリーンショット 2020-05-05 23 33 55" src="https://user-images.githubusercontent.com/56591/81078231-eadc6e80-8f28-11ea-82fc-91d9847bb192.png">

直ったのを確認しました！
