### ISSUE TITLE
添付ファイルの横に「？」アイコンを表示して…

### ISSUE THREAD

**Issue by koron** [vim-jp/slacklog-generator#55]
#2 より派生

以下の文言を表示

    画像が見れない場合 vim-jp.slack.com にログインすると見れるようになります

**Comment by thinca** [comment]
> 画像が見れない場合 vim-jp.slack.com にログインすると見れるようになります

これは、画像は Slack への直リンにしてしまおうとしていた時の案ですね。token なしの URL で画像を埋め込んで、ログイン済みなら画像が見えるようになる…と言うのを考えていました。
画像も全部自前で持つようにしたので、このメッセージは表示する必要はないかと思います。

**Comment by koron** [comment]
では worksforme ってことで閉じますね。
