### ISSUE TITLE
pages_diff.sh 消す

### ISSUE THREAD

**Issue by koron** [vim-jp/slacklog-generator#60]
もういらないはず

**Comment by kuuote** [comment]
消すの、site_diffの方では無いっけ

**Comment by koron** [comment]
jekyll build が遅かったんで、site_diff でイテレーションするのがきつかった。
でもそれがなくなれば最終成果物だけ比較できればシンプルになるって話です。

CIとかドキュメントも修正がいるのでちょっとだけめんどいですが。

**Comment by kuuote** [comment]
完全理解

**Comment by koron** [comment]
やります
