### ISSUE TITLE
build.shでハードリンクを使う

### ISSUE THREAD

**Issue by kuuote** [vim-jp/slacklog-generator#73]
無駄にファイルをコピーしてて遅いのでハードリンクを使うようにしたい
cpのLinux以外での挙動を知らないので(対応してるのか、エラーを吐くのか通常動作にフォールバックされるのかとか)試し次第やるかやらないか決める予定です

**Comment by koron** [comment]
Windowsはディレクトリのハードリンクできないです。
symblic link 相当(junktion)は作れる条件が厳しい(開発者モードじゃなきゃダメ、とか)。
ショートカットによる実装は読めないやついるかも。

rsync 使うのはどうでしょ?

**Comment by kuuote** [comment]
一旦rsyncがあれば使うみたいな感じでやってみます

**Comment by k-takata** [comment]
> Windowsはディレクトリのハードリンクできないです。

それはUnixも同じような。

Windows の場合は:

* junction: ディレクトリだけで使える symlink のようなもの。特別な権限は不要。必ず絶対パス。
* symlink: Unix の symlink とほぼ同等。ただし、作成には管理者権限か開発者モードが必要。
* hard link: Unix の hard link とほぼ同等。ディレクトリ不可。特別な権限は不要。

Windows でも rsync が使えるなら ln も使えると思います。

**Comment by kuuote** [comment]
やる意味なさそうなので閉じます
