### ISSUE TITLE
フロントエンド用の静的ファイルを移動する

### ISSUE THREAD

**Issue by koron** [vim-jp/slacklog-generator#83]
#61 からの派生

現在プロジェクトルートにある assets/ と favicon.ico を一か所にまとめたい。
妥当だろうか?

変更のイメージ

* assets/ → assets/
* favicon.ico → assets/.../favicon.ico

cc @heavenshell

**Comment by heavenshell** [comment]
https://github.com/vim-jp/slacklog-generator/pull/84
で対応しました！

**Comment by koron** [comment]
done by 84
