### ISSUE TITLE
Slack への参加方法ページへのリンクが切れている

### ISSUE THREAD

**Issue by tennashi** [vim-jp/slacklog-generator#92]
https://vim-jp.org/slacklog/ にある
`参加方法、各チャンネルの概要等はこちらを参照して下さい。` の `こちら`
https://vim-jp.org/slacklog/docs/chat.html
これが 404 になってる

**Comment by koron** [comment]
正しくは <https://vim-jp.org/docs/chat.html> かな?
変にシステマティックにURLを生成しようとして失敗した感。
