### ISSUE TITLE
大きな埋め込みファイルは表示しないようにする

### ISSUE THREAD

**Issue by koron** [vim-jp/slacklog-generator#98]
#76 において plain/text の埋め込みがされるようになった。

しかしめちゃくちゃデカいJSONとか埋め込まれててぐんにょりするので
ある程度の大きさで足切りしたい。

**Comment by raa0121** [comment]
files の中に size があるので、これを見るようにしますかね。
Slack で話題になったログファイルは 210,372 にだったので、 100,000 位上だと表示しない とかですかね。

**Comment by koron** [comment]
100KiB ってことで 102400 にしませんか?

**Comment by raa0121** [comment]
102400 両化位です
